### PR TITLE
Refs [Task] [#37319] build men, women,kids clothes and handbag & shoes

### PR DESCRIPTION
**Pull request by tripro9x12**
https://edu-redmine.sun-asterisk.vn/issues/37319

### CODE REVIEW

**Comment by tripro9x12** [comment]
ready

**Comment by manhnt-0960** [comment]
conflicted

**Comment by tripro9x12** [comment]
ready

**Comment by manhnt-0960** [comment]
commented
check tên task

**Comment by tripro9x12** [comment]
ready

**Pull request merged**
